---
- name: Gather remote facts
  setup: {}

- name: Set domain controllers as DNS servers
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses: "{{ domain_controller_ip }}"

- name: Set domain root
  set_fact:
    domain_root_path: DC={{ dc_domain.split('.') | join(',DC=') }}

- name: Set Workstations OU
  set_fact:
    workstations_ou: "ou=Workstations,{{ domain_root_path }}"
  when: inventory_hostname in groups['endpoints']

- name: Set Servers OU
  set_fact:
    servers_ou: "ou=Servers,{{ domain_root_path }}"
  when: inventory_hostname in groups['servers']

- name: Join workstation to the domain
  win_domain_membership:
    dns_domain_name: "{{ dc_domain }}"
    hostname: "{{ ansible_env.COMPUTERNAME }}"
    domain_admin_user: "{{ domain_admin }}@{{ dc_domain }}"
    domain_admin_password: "{{ domain_admin_password }}"
    domain_ou_path: "{{ workstations_ou }}"
    state: domain
  when: inventory_hostname in groups['endpoints']

- include_tasks: reboot.yml
  when: inventory_hostname in groups['endpoints']

- name: Join server to the domain
  win_domain_membership:
    dns_domain_name: "{{ dc_domain }}"
    hostname: "{{ ansible_env.COMPUTERNAME }}"
    domain_admin_user: "{{ domain_admin }}@{{ dc_domain }}"
    domain_admin_password: "{{ domain_admin_password }}"
    domain_ou_path: "{{ servers_ou }}"
    state: domain
  when: inventory_hostname in groups['servers']

- include_tasks: reboot.yml
  when: inventory_hostname in groups['servers']

- name: Ensure domain users can RDP on any workstation
  win_group_membership:
    name: Remote Desktop Users
    members: "{{ dc_domain }}\\Domain Users"
  when: inventory_hostname in groups['endpoints']
