---
- name: Install FortiAgent
  win_shell: fortiagent.exe --startup auto install 
  args:
    chdir: C:\temp\
    executable: cmd

- name: Start FortiAgent
  win_shell: fortiagent.exe start
  args:
    chdir: C:\temp\
    executable: cmd

- include_tasks: roles/wait.yml
