---
- name: ADD FAZ DEVICE
  connection: httpapi
  gather_facts: false
  hosts: FortiAnalyzer

  tasks:
    - name: DISCOVER AND ADD DEVICE A VIRTUAL FORTIGATE SPECIFYING ALL PARAMETERS
      faz_device:
        adom: "root"
        device_ip: "10.7.220.151"
        device_password: "fortinet"
        device_unique_name: "ansible-fgt01"
        device_username: "ansible"
        mgmt_mode: "faz"
        os_minor_vers: 4
        os_type: "fos"
        os_ver: "6.0"
        platform_str: "FortiGate-VM64"
        mode: "add"
        device_serial: "FGVM04TM18000391"

    - name: DISCOVER AND ADD DEVICE A VIRTUAL FORTIGATE SPECIFYING BARE PARAMS
      faz_device:
        adom: "root"
        device_ip: "10.7.220.152"
        device_password: "fortinet"
        device_unique_name: "ansible-fgt02"
        device_username: "ansible"
        mgmt_mode: "faz"
        platform_str: "FortiGate-VM64"
        mode: "add"
        device_serial: "FGVM04TM18000392"

