- hosts: dc 
  gather_facts: no
  roles:
    - role: bootstrap
    - role: domain-controller
#    - role: fortisiem-agent

- hosts: endpoints 
  gather_facts: no
  roles:
    - role: bootstrap
    - role: domain-member
    - role: sysmon
#    - role: fortisiem-agent

- hosts: servers
  gather_facts: no
  roles:
    - role: bootstrap
    - role: domain-member
    - role: sysmon
