- hosts: endpoint_02
  gather_facts: no
  vars:
      hostname: Endpoint02
      dns_name: fortilabs.local
      initial_domain_admin: administrator
      initial_domain_admin_password: 40Net123#

  roles:
    - role: bootstrap
    - role: disable-windowsdefender
    - role: domain-member
    - role: sysmon
    - role: fortisiem-agent
