---
- name: GET RESULTS FROM REPORT
  hosts: FortiSIEM_MSP
  connection: local
  gather_facts: False

  tasks:
    - name: MSP SUBMIT REPORT
      fsm_report_query:
        host: "{{ inventory_hostname }}"
        username: "testOrg/api_user"
        password: "{{ password }}"
        ignore_ssl_errors: "enable"
        report_file_path: "/root/msp-report.xml"
        export_json_to_screen: "enable"
        export_json_to_file_path: "/root/msp_report.json"
        export_xml_to_file_path: "/root/msp__report.xml"


