---

- include_tasks: wait.yml

- name: Disable Windows Defender
  win_shell: |
    Set-MpPreference -DisableRealtimeMonitoring $True -Force
    Set-MpPreference -DisableBehaviorMonitoring $True -Force
    Set-MpPreference -DisableIntrusionPreventionSystem $True -Force
    Set-MpPreference -ScanScheduleDay Never -Force
    Set-MpPreference -RemediationScheduleDay Never -Force

#Set-MpPreference -DisableIntrusionPreventionSystem $true -DisableIOAVProtection $true -DisableRealtimeMonitoring $true -DisableScriptScanning $true -EnableControlledFolderAccess Disabled -EnableNetworkProtection AuditMode -MAPSReporting Disabled -SubmitSamplesConsent NeverSend -DisableBehaviorMonitoring $true -Force
