---
- win_copy:
   src: "{{ fsmagent_installer }}"
   dest: "C:\\temp\\"
   remote_src: no

- name: Deploy Windows Agent template settings
  win_copy:
   content: |
      <InstallConfig Version="1">
      <Org>
         <ID>{{ fsm_org_id }}</ID>
         <Name>{{ fsm_org }}</Name>
      </Org>
      <Super>
         <Name>{{ hostvars['fsm_super']['ansible_host'] }}</Name>
         <Port>443</Port>
      </Super>
      <Registration>
         <Username>{{ fsmagent_admin }}</Username>
         <Password>{{ fsmagent_password }}</Password>
      </Registration>
      <Proxy />
      <SSLCertificate>ignore</SSLCertificate>
      </InstallConfig>
   dest: "C:\\temp\\InstallSettings.xml"
   remote_src: no

- name: Install FortiSIEM Windows Agent
  win_package:
    path: "C:\\temp\\{{ fsmagent_installer }}"
    arguments:
      - /install
      - /quiet
      - /log c:\temp\fsmagent.txt
    chdir: "C:\\temp\\"
    product_id: "FSM"
