---
- name: GET MSP CMDB DEVICES
  hosts: FortiSIEM_MSP
  connection: local
  gather_facts: False

  tasks:
    - name: GET MSP SIMPLE DEVICE LIST FROM CMDB
      fsm_cmdb_devices:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ignore_ssl_errors: "enable"
        mode: "short_all"
        export_json_to_screen: "enable"
        export_json_to_file_path: "/root/msp_testOrg_simpleDeviceList.json"
        export_xml_to_file_path: "/root/msp_testOrg_xml_simpleDeviceList.xml"


    - name: GET MSP SIMPLE DEVICE LIST FROM CMDB IP RANGE
      fsm_cmdb_devices:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ignore_ssl_errors: "enable"
        mode: "ip_range"
        ip_range: "10.0.0.1-10.0.0.255"

    - name: GET MSP DETAILED INFO ON ONE DEVICE
      fsm_cmdb_devices:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ignore_ssl_errors: "enable"
        mode: "detailed_single"
        ip: "10.7.220.34"