---

- include_tasks: roles/wait.yml

- name: Gather remote facts
  setup: {}

- debug:
    var: ansible_distribution

- name: Disable Windows Defender
  win_shell: |
     Set-MpPreference -DisableIntrusionPreventionSystem $true -DisableIOAVProtection $true -DisableRealtimeMonitoring $true -DisableScriptScanning $true -EnableControlledFolderAccess Disabled -EnableNetworkProtection AuditMode -Force -MAPSReporting Disabled -SubmitSamplesConsent NeverSend
  when: ansible_distribution == "Microsoft Windows 10 Enterprise Evaluation"
