---
- include_tasks: wait.yml

- name: Install AD-Domain-Services feature
  win_feature:
    name: AD-Domain-Services
    include_management_tools: true
    include_sub_features: true
    state: present
  register: adds_result

- name: Collect ADDS provision result
  debug:
    msg: "{{adds_result}}"

- name: Fix PowerShell modules installation
  win_shell: |
     [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
     Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
     Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
     [Net.ServicePointManager]::SecurityProtocol = "tls12"

- name: Ensure xActiveDirectory PS DSC module is installed
  win_psmodule:
    name: xActiveDirectory
    state: present

- name: Creating a windows domain
  win_domain:
    dns_domain_name: "{{ dc_domain }}"
    safe_mode_password: "40Net123#"
  register: domain_creation

- include_tasks: reboot.yml
  when: domain_creation.reboot_required

- name: Promote Domain Controller
  win_domain_controller:
    dns_domain_name: "{{ dc_domain }}"
    domain_admin_user: "{{ domain_admin }}@{{ dc_domain }}"
    domain_admin_password: "{{ domain_admin_password }}"
    safe_mode_password: "{{ domain_admin_password }}"
    state: domain_controller
  register: dc_promotion


- name: Waiting to the domain to become available
  win_dsc:
    resource_name: xWaitForADDomain
    DomainName: "{{ dc_domain }}"
    RetryCount: 100
    RetryIntervalSec: 10

- include_tasks: wait.yml

- name: Set a weak password policy
  win_command: powershell.exe -
  args:
    stdin: "Set-ADDefaultDomainPasswordPolicy -MinPasswordLength 1 -ComplexityEnabled $False -Identity {{ dc_domain }}"

