uac_enabled: false
deploy_dc: true 
populate_structure: true 
populate_users: true
gpo_disable_windows_defender: true 
gpo_windows_firewall: true
gpo_servers_audit_policy: true
gpo_workstations_audit_policy: true
gpo_domain_controller_audit_policy: true
root_ou: Employees
child_ous:
  - Finance
  - IT
  - Marketing
  - Operations
  - Sales
