---
- name: STATUS DISCOVERY JOBS
  hosts: FortiSIEM
  connection: local
  gather_facts: False

  tasks:
    - name: GET STATUS FOR A DISCOVERY
      fsm_discovery:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ignore_ssl_errors: "enable"
        export_json_to_screen: "enable"
        export_json_to_file_path: "/root/disco_status.json"
        export_xml_to_file_path: "/root/disco_status.xml"
        type: "status"
        task_id: "2508033"
