# Configure DNS Feature
- name: Install DNS SubFeature
  win_feature:
    name: DNS
    include_sub_features: true
    include_management_tools: true
    state: present
  register: dns_result

- name: Collect dns provision result
  debug:
    msg: "{{dns_result}}"

