---
- name: Install IIS Web-Server with sub features and management tools
  win_feature:
    name: Web-Server,web-asp-Net,Web-Http-Logging
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature

- include_tasks: roles/reboot.yml
  when: win_feature.reboot_required

- name: Install MSDeploy
  win_chocolatey:
    name:
    - msdeploy
