---
- name: cloning git repo
  raw: git clone https://github.com/rolando-anton/FSM-Demo_IIS_MSSQL_SuperSecureBank/ C:\Windows\Temp\SecureBank_Demo

- name: Restore SuperSecureBank Database
  win_shell: invoke-sqlcmd -inputfile 'C:\Windows\Temp\SecureBank_Demo\aio.sql' -serverinstance "IIS-MSSQL\SQLEXPRESS" -database "master"

- name: Executing MSSQL Auditing Scripts
  win_shell: invoke-sqlcmd -inputfile 'C:\Windows\Temp\SecureBank_Demo\PH_Audit_Setup.sql' -serverinstance "IIS-MSSQL\SQLEXPRESS" -database "master"

- name: Creating Read Only User for Performance Monitoring
  win_shell: invoke-sqlcmd -inputfile 'C:\Windows\Temp\SecureBank_Demo\new-ro-users.sql' -serverinstance "IIS-MSSQL\SQLEXPRESS" -database "master"

- name: Remove Default Web Site
  win_iis_website:
    name: "Default Web Site"
    state: absent

- name: Unzip Site Backup
  win_unzip:
    src: 'C:\Windows\Temp\SecureBank_Demo\site.zip'
    dest: 'C:\Windows\Temp\SecureBank_Demo\'

- name: Creating Application Pool in IIS
  win_iis_webapppool:
    name: SuperSecureBankPool
    state: started
    attributes:
      managedRuntimeVersion: v4.0
      managedPipelineMode: Integrated
      processModel.identityType: SpecificUser
      processModel.userName: "{{ ansible_user  }}"
      processModel.password: "{{ ansible_password }}"
      processModel.loadUserProfile: true

- name: Configure IIS Site
  win_iis_website:
    name: SuperSecureBank
    state: started
    port: 80
    application_pool: SuperSecureBankPool
    physical_path: C:\inetpub\wwwroot
    register: website

- name: Deploy SuperSecureBank Web Application
  win_shell: |
    $msdeploypath = Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\IIS Extensions\MSDeploy\*" | select -ExpandProperty InstallPath
    $msdeployexe = "msdeploy.exe"
    $msdeploy = $msdeploypath + $msdeployexe
    $msdeployArgs = @(
    "-verb:sync",
    "-source:package=C:\Windows\Temp\SecureBank_Demo\site\SuperSecureBank.zip",
    "-dest:auto,includeAcls='False'",
    "-disableLink:AppPoolExtension",
    "-disableLink:ContentExtension",
    "-disableLink:CertificateExtension",
    "-setParamFile:C:\Windows\Temp\SecureBank_Demo\site\SuperSecureBank.SetParameters.xml"
    "-verbose"
    )
    Start-Process $msdeploy -NoNewWindow -ArgumentList $msdeployArgs
