- hosts: dc,endpoints
  gather_facts: no
  tasks:
    - include: first-boot.yml
 
- hosts: dc 
  gather_facts: no
  roles:
    - role: bootstrap
    - role: domain-controller

- hosts: endpoints 
  gather_facts: no
  roles:
    - role: bootstrap
    - role: domain-member
    - role: office365
    - role: sysmon
