- hosts: dc 
  gather_facts: no
  roles:
    - role: bootstrap
    - role: domain-controller
#    - role: fortisiem-agent

- hosts: endpoints 
  gather_facts: no
  roles:
    - role: bootstrap
    - role: domain-member
    - role: office365
    - role: sysmon
#    - role: fortisiem-agent

- hosts: servers
  gather_facts: no
  roles:
    - role: bootstrap
    - role: domain-member
    - role: sysmon

- hosts: gateway
  gather_facts: no
  vars:
    ansible_connection: ssh
  tasks:
  - name: Clear device identity database
    raw: diagnose user device clear

- hosts: gateway
  gather_facts: no
  vars:
    ansible_connection: httpapi
  collections:
  - fortinet.fortios
  roles:
    - fos-ldap-server

#- hosts: analyzer
#  gather_facts: no
#  vars:
#    ansible_connection: ssh
#  roles:
#    - faz_to_fsm
