- hosts: dc
  gather_facts: no
  vars:
    dc_domain: fortidemo.local
    deploy_dc: true
    populate_structure: true
    populate_users: true
    gpo_disable_windows_defender: true
    gpo_windows_firewall: false
    gpo_servers_audit_policy: true
    gpo_workstations_audit_policy: false
    gpo_domain_controller_audit_policy: true
  roles:
    - role: bootstrap
    - role: domain-controller
    - role: sysmon
