---
- name: Configure LDAP server entries.
  fortios_user_ldap:
    vdom:  "{{ vdom }}"
    state: "present"
    user_ldap:
      name: "DMEVALS_DC"
      server: "{{ domain_controller_ip }}"
      port: "389"
      cnid: "sAMAccountName"
      dn: "DC={{ dc_domain.split('.') | join(',DC=') }}"
      username: "cn={{ domain_admin }},cn=users,DC={{ dc_domain.split('.') | join(',DC=') }}"
      password: "{{ domain_admin_password }}"
      secure: "disable"
      type: "regular"

- name: Configure Fortinet Single Sign On (FSSO) server.
  fortios_user_fsso_polling:
    vdom:  "{{ vdom }}"
    state: "present"
    user_fsso_polling:
      id:  "0"
      ldap_server: "DMEVALS_DC"
      server: "{{ domain_controller_ip }}"
      port: "389"
      user: "{{ domain_admin }}"
      password: "{{ domain_admin_password }}"
      adgrp:
        - name: "OU=Employees,DC=dmevals,DC=local"
        - name: "OU=Finance,OU=Employees,DC=dmevals,DC=local"
        - name: "OU=IT,OU=Employees,DC=dmevals,DC=local"
        - name: "OU=Marketing,OU=Employees,DC=dmevals,DC=local"
        - name: "OU=Operations,OU=Employees,DC=dmevals,DC=local"
        - name : "OU=Sales,OU=Employees,DC=dmevals,DC=local"
      status: enable
