---
- name: Install AD-Domain-Services feature
  win_feature:
    name: AD-Domain-Services
    include_management_tools: true
    include_sub_features: true
    state: present
  register: adds_result

- name: Collect ADDS provision result
  debug:
    msg: "{{adds_result}}"

- name: Ensure xActiveDirectory PS DSC module is installed
  win_psmodule:
    name: xActiveDirectory
    state: present

- name: Creating a windows domain
  win_domain:
    dns_domain_name: "{{ dns_name }}"
    safe_mode_password: "40Net123#"
  register: domain_creation

- name: Reboot if domain was just created
  win_reboot:
    connect_timeout: 15
    post_reboot_delay: 15
  when: domain_creation.reboot_required

- name: Promote Domain Controller
  win_domain_controller:
    dns_domain_name: "{{ dns_name }}"
    domain_admin_user: "{{ initial_domain_admin }}@{{ dns_name }}"
    domain_admin_password: "{{ initial_domain_admin_password }}"
    safe_mode_password: "{{ initial_domain_admin_password }}"
    state: domain_controller
    log_path: C:\Windows\Temp\promotion.txt
  register: dc_promotion


- name: Ensure domain is available
  win_dsc:
    resource_name: xWaitForADDomain
    DomainName: "{{ dns_name }}"
    RetryCount: 100
    RetryIntervalSec: 10

- name: Set a weak password policy
  win_command: powershell.exe -
  args:
    stdin: "Set-ADDefaultDomainPasswordPolicy -MinPasswordLength 1 -ComplexityEnabled $False -Identity {{ dns_name }}"

