---
- include_tasks: wait.yml

- name: "Install GroupPolicyDSC"
  win_psmodule:
    name: GroupPolicyDSC
    state: present

- name: Set facts to import GPO
  set_fact:
    GPOName: "Disable Windows Defender"
    GPOImportPath: "c:\\temp\\disable_windows_defender\\"
    domain_root_path: "DC={{ dc_domain.split('.') | join(',DC=') }}"

- name: Set OUs to apply the GPO
  set_fact:
    OU_list:
      - "OU=Servers,{{ domain_root_path }}"
      - "OU=Workstations,{{ domain_root_path }}"


- win_copy:
   src: files/gpo/disable_windows_defender
   dest: "c:\\temp\\"
   remote_src: no

- include: gpo.yml
