- include: deploy.yml
  when: deploy_dc | bool
- include: populate_structure.yml
  when: populate_structure | bool
- include: populate_users.yml
  when: populate_users | bool
- include: gpo_disable_windows_defender.yml
  when: gpo_disable_windows_defender | bool
- include: gpo_powershell_execution_policy.yml
  when: gpo_powershell_execution_policy | bool
